### PR TITLE
refine permissions

### LINKED ISSUE #424: Fine-Grained Permissions
@dav3r requested to fine grain the indivdual permissions for IAM roles to something similar like this - https://github.com/cisagov/cool-assessment-terraform/blob/08cf22ebb0893d9b762a5329097a44f69e4200ff/provisionassessment_policy.tf.

### PR DESCRIPTION
**Pull request by zenine07**
Instead of a wildcard for a service, refine permissions to only necessary permissions.

### CODE REVIEW

**Review by dav3r — CHANGES_REQUESTED** [review]
I know it is more work, but our standard practice is to specifically list all of the required permissions without any wildcards.  The reason for this is to ensure that no additional permissions can "sneak in" if AWS adds a new permission that matches one of the existing patterns.  Additionally, it is nice from a transparency perspective to be able to look at the list of permissions and see their full names.

**Comment by zenine07** [comment]
I've refined the permissions even more. I personally think this way is less readable and understandable, but this should be all the permissions.

**Comment by dav3r** [comment]
Thanks @zenine07 - I understand your readability concerns with such a large number of permissions.  I have a couple suggestions that I think may help:

1) Alphabetize the permissions within each service; you already have the services alphabetized which is good.  You had them alphabetized previously, so I didn't mention it earlier, but this is another one of our standard practices.

2) This one is a bit more work, but I think it improves the code readability (at the expense of adding more code, but I feel it's worthwhile here): Make one policy per service, name the policy after the service, and ensure that the policy description mentions the name of the service.

**Comment by zenine07** [comment]
@dav3r  I can go through and alphabetize the services, but I can't do one policy per service. AWS has a limit to the number of policies that can be attached to a role. That limit is 10.

**Comment by dav3r** [comment]
> @dav3r I can go through and alphabetize the services, but I can't do one policy per service. AWS has a limit to the number of policies that can be attached to a role. That limit is 10.

Ah right- I forgot about that limit!  Can the policy descriptions at least mention the service names that are in the policy?

**Comment by zenine07** [comment]
Yeah, I think I should be able to get away with that. I'm not sure what the policy name limit is, but I'll check if that works.

**Comment by dav3r** [comment]
> Yeah, I think I should be able to get away with that. I'm not sure what the policy name limit is, but I'll check if that works.

Even if the policy names can't include the list of services, as long as the policy description mentions them, I think that will be fine.

**Comment by zenine07** [comment]
Made those updates. I checked the policy name limits and there's a 128 character limit. I verified that all the policy names are within that limit. I also updated the descriptions and sorted the permissions.

**Review by dav3r — APPROVED** [review]
This looks great now- thanks for being flexible with these changes! 🚀

**Pull request merged**
